/**
 * public-api-projects.ts — Tucaken projects data layer (RDS via BFF).
 *
 * Reads the in-cluster `public-api` BFF's public projects endpoints; the
 * site holds no AWS credentials and never touches RDS directly. Projects
 * are generated by the Tucaken case-study pipeline from synced GitHub
 * repositories and gated server-side by `visibility='public'` — this
 * module can only ever see what the owner deliberately published.
 *
 * Upstream contract (ai-applications api/public-api/src/routes/projects.ts):
 *   GET /public/projects/:username        → { items: PublicProjectCard[], count }
 *   GET /public/projects/:username/:slug  → PublicCaseStudy | 404
 *
 * Env:
 *   PUBLIC_API_URL              — in-cluster BFF base URL
 *                                 (default: http://public-api.public-api:3001)
 *   PORTFOLIO_GITHUB_USERNAME   — the owner's GitHub username, the public
 *                                 identity the BFF keys projects on
 *                                 (default: Nelson-Lamounier)
 *
 * Gotchas: runs at build time with no cluster access — every read
 * degrades gracefully ([] / null) so Docker builds and ISR prerenders
 * succeed against an unreachable BFF, matching the articles data layer.
 */

// Same default as the articles layer: Kubernetes service DNS, resolved
// only from inside the cluster. Build-time fetches fail fast and degrade.
const PUBLIC_API_URL =
  process.env.PUBLIC_API_URL || 'http://public-api.public-api:3001'

/** The BFF keys public projects on the owner's GitHub username. */
const PORTFOLIO_GITHUB_USERNAME =
  process.env.PORTFOLIO_GITHUB_USERNAME || 'Nelson-Lamounier'

/** ISR fetch-cache TTL — matches the BFF's s-maxage=300. */
const REVALIDATE_SECONDS = 300

// ========================================
// Upstream response types (JSON-stable contract with public-api)
// ========================================

/** One grid card from GET /public/projects/:username. */
export interface PublicProjectCard {
  slug: string
  name: string
  tagline: string | null
  type: string
  shape: string
  roleExhibited: string
  caseStudyStatus: string | null
  startedAt: string | null
  lastActivityAt: string | null
  updatedAt: string
  tags: string[]
  stack: Array<{ category: string; name: string }>
  repositories: string[]
}

export interface CaseStudyComponent {
  id: string
  name: string
  kind: string
  order_index: number
}
export interface CaseStudyRepository {
  component_id: string
  repository_full_name: string
  subpath: string
}
export interface CaseStudyDecision {
  title: string
  context: string | null
  decision: string | null
  consequences: string | null
  confidence: string
  order_index: number
}
export interface CaseStudyHighlight {
  title: string
  description: string | null
  order_index: number
}
export interface CaseStudyChallenge {
  problem: string
  solution: string | null
  order_index: number
}
export interface CaseStudyStackItem {
  category: string
  name: string
  justification: string | null
  order_index: number
}
export interface CaseStudyDepthMarkers {
  has_tests: boolean
  test_coverage_signal: string
  has_ci: boolean
  ci_maturity: string
  documentation_density: string
  has_deployment_evidence: boolean
  deployment_url: string | null
  refactor_count: number
}
export interface CaseStudyArchitecture {
  diagram_format: string
  diagram_source: string
}
export interface CaseStudyResumeBullets {
  angle: string
  bullets: string[]
}

/** Full case study from GET /public/projects/:username/:slug. */
export interface PublicCaseStudy {
  username: string
  slug: string
  name: string
  tagline: string | null
  pitch: string | null
  type: string
  shape: string
  status: string
  roleExhibited: string
  startedAt: string | null
  endedAt: string | null
  lastActivityAt: string | null
  updatedAt: string
  components: CaseStudyComponent[]
  repositories: CaseStudyRepository[]
  decisions: CaseStudyDecision[]
  highlights: CaseStudyHighlight[]
  challenges: CaseStudyChallenge[]
  stack: CaseStudyStackItem[]
  depthMarkers: CaseStudyDepthMarkers | null
  architecture: CaseStudyArchitecture | null
  resumeBullets: CaseStudyResumeBullets[]
  tags: string[]
}

// ========================================
// Fetch helpers
// ========================================

async function getJson<T>(path: string): Promise<T | null> {
  const res = await fetch(`${PUBLIC_API_URL}${path}`, {
    next: { revalidate: REVALIDATE_SECONDS },
  })
  // Non-OK (404 private project, 5xx BFF trouble) maps to null rather than
  // throwing: callers render notFound()/empty state and ISR keeps working.
  if (!res.ok) return null
  return (await res.json()) as T
}

// ========================================
// Public data-layer API
// ========================================

/**
 * Fetch the owner's public project cards, most recently active first.
 *
 * @returns [] on any failure — the grid page must render (and the Docker
 *          build must succeed) with the BFF unreachable.
 */
export async function queryPublicProjects(): Promise<PublicProjectCard[]> {
  try {
    const data = await getJson<{ items: PublicProjectCard[]; count: number }>(
      `/public/projects/${encodeURIComponent(PORTFOLIO_GITHUB_USERNAME)}`,
    )
    return data?.items ?? []
  } catch (error) {
    console.error('[public-api-projects] queryPublicProjects failed:', error)
    return []
  }
}

/**
 * Fetch one public case study by slug. Null when missing, not public, or
 * the BFF is unreachable — the page maps null to notFound().
 */
export async function getPublicCaseStudy(
  slug: string,
): Promise<PublicCaseStudy | null> {
  try {
    return await getJson<PublicCaseStudy>(
      `/public/projects/${encodeURIComponent(PORTFOLIO_GITHUB_USERNAME)}/${encodeURIComponent(slug)}`,
    )
  } catch (error) {
    console.error('[public-api-projects] getPublicCaseStudy failed:', error)
    return null
  }
}
