/** @format */

import { NextResponse } from 'next/server';
import { timingSafeEqual } from 'node:crypto';
import { register } from '@/lib/observability/metrics';

// ========================================
// Bearer Token Authentication
// ========================================

/** SSM parameter path for the bearer token (set by monitoring EC2 at boot) */
const METRICS_TOKEN_SSM_PATH = process.env.METRICS_TOKEN_SSM_PATH || '';
const METRICS_BEARER_TOKEN = process.env.METRICS_BEARER_TOKEN?.trim() || '';
const IS_PRODUCTION = process.env.NODE_ENV === 'production';

/** Token cache TTL — avoids SSM API calls on every Prometheus scrape */
const TOKEN_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

/** How long to wait for SSM before giving up (prevents hanging) */
const SSM_TIMEOUT_MS = 3_000;

/** How long to wait before retrying after an SSM failure */
const SSM_RETRY_BACKOFF_MS = 60 * 1000; // 1 minute

let cachedToken: string | null = null;
let tokenFetchedAt = 0;
let lastFailureAt = 0;

type MetricsTokenResult =
  | { status: 'disabled'; token: null }
  | { status: 'ready'; token: string }
  | { status: 'unavailable'; token: null; reason: string };

/**
 * Resolve the bearer token from an explicit environment variable or SSM
 * Parameter Store. The SSM token is generated by the monitoring EC2 at boot
 * and stored as a SecureString at /{namePrefix}/prometheus/metrics-bearer-token.
 *
 * Local/test environments can run without a configured SSM path, but production
 * fails closed when the token cannot be loaded.
 */
async function getMetricsToken(): Promise<MetricsTokenResult> {
  if (METRICS_BEARER_TOKEN) {
    return { status: 'ready', token: METRICS_BEARER_TOKEN };
  }

  if (!METRICS_TOKEN_SSM_PATH) {
    return IS_PRODUCTION
      ? {
          status: 'unavailable',
          token: null,
          reason: 'METRICS_TOKEN_SSM_PATH is not configured',
        }
      : { status: 'disabled', token: null };
  }

  // Return cached token if still valid
  if (cachedToken && Date.now() - tokenFetchedAt < TOKEN_CACHE_TTL_MS) {
    return { status: 'ready', token: cachedToken };
  }

  // Back off if SSM recently failed (avoids hammering a broken path)
  if (lastFailureAt && Date.now() - lastFailureAt < SSM_RETRY_BACKOFF_MS) {
    return cachedToken
      ? { status: 'ready', token: cachedToken }
      : {
          status: 'unavailable',
          token: null,
          reason: 'SSM token fetch is in retry backoff',
        };
  }

  try {
    // Lazy-import SSM client to avoid loading it when auth is disabled
    const { SSMClient, GetParameterCommand } = await import('@aws-sdk/client-ssm');
    const ssm = new SSMClient({ region: process.env.AWS_REGION ?? 'eu-west-1' });

    // AbortController with 3s timeout prevents hanging when SSM is unreachable
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), SSM_TIMEOUT_MS);

    try {
      const result = await ssm.send(
        new GetParameterCommand({
          Name: METRICS_TOKEN_SSM_PATH,
          WithDecryption: true,
        }),
        { abortSignal: controller.signal },
      );

      const token = result.Parameter?.Value?.trim() ?? '';
      if (!token) {
        throw new Error(`SSM parameter ${METRICS_TOKEN_SSM_PATH} is empty`);
      }

      cachedToken = token;
      tokenFetchedAt = Date.now();
      lastFailureAt = 0; // reset failure state on success
      return { status: 'ready', token: cachedToken };
    } finally {
      clearTimeout(timeout);
    }
  } catch (err) {
    lastFailureAt = Date.now();
    console.warn(
      `[metrics] SSM token fetch failed (will retry in ${SSM_RETRY_BACKOFF_MS / 1000}s):`,
      err instanceof Error ? err.message : String(err),
    );
    return cachedToken
      ? { status: 'ready', token: cachedToken }
      : {
          status: 'unavailable',
          token: null,
          reason: 'SSM token fetch failed',
        };
  }
}

function isValidBearerToken(authHeader: string | null, expectedToken: string) {
  if (!authHeader?.startsWith('Bearer ')) {
    return false;
  }

  const actualToken = authHeader.slice('Bearer '.length);
  const actual = Buffer.from(actualToken);
  const expected = Buffer.from(expectedToken);

  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

// ========================================
// GET /api/metrics
// ========================================

/**
 * GET /api/metrics
 * Returns metrics in Prometheus text format.
 *
 * Authentication:
 * - In production (ECS), validates a bearer token stored in SSM.
 * - In local dev (no SSM), falls through without auth.
 *
 * This endpoint is scraped by Prometheus every 15-30 seconds.
 */
export async function GET(request: Request) {
  try {
    // ── Bearer Token Validation ──
    const tokenResult = await getMetricsToken();

    if (tokenResult.status === 'unavailable') {
      console.error(`[metrics] Authentication unavailable: ${tokenResult.reason}`);
      return NextResponse.json(
        { error: 'Metrics authentication is not configured' },
        { status: 503 },
      );
    }

    if (
      tokenResult.status === 'ready' &&
      !isValidBearerToken(request.headers.get('authorization'), tokenResult.token)
    ) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 },
      );
    }

    // ── Return Prometheus Metrics ──
    const metrics = await register.metrics();

    return new NextResponse(metrics, {
      headers: {
        'Content-Type': register.contentType,
        'Cache-Control': 'no-store, no-cache, must-revalidate',
      },
    });
  } catch (error) {
    console.error('Error generating metrics:', error);

    // Return minimal metrics even on error
    return new NextResponse('# Error generating metrics\nnextjs_up 0\n', {
      status: 500,
      headers: {
        'Content-Type': 'text/plain; version=0.0.4',
      },
    });
  }
}

// ── Route Segment Config ─────────────────────────────────────────────────────
// Explicitly pin to the Node.js runtime. prom-client relies on Node-only APIs
// (process.version, process.hrtime, Buffer) which are unavailable in the Edge
// Runtime. Without this declaration Next.js emits build warnings for every
// import that transitively reaches prom-client.
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const revalidate = 0;
