/**
 * Projects Page — Tucaken-generated projects (RDS via the public-api BFF)
 *
 * Lists the owner's public projects: entities generated by the Tucaken
 * case-study pipeline from synced GitHub repositories, gated server-side
 * by visibility='public'. Cards link to the native /projects/[slug]
 * case-study page.
 *
 * Fallback: while the projects BFF endpoint is not yet deployed (or no
 * project has been made public), the page falls back to the legacy
 * behaviour of rendering published articles as project cards, so the
 * route never renders empty during the migration window. Remove the
 * fallback once the projects source is stable in production.
 *
 * Route: /projects
 */

import { type Metadata } from 'next'
import { type ReactNode } from 'react'

// ISR: revalidate every hour so the in-cluster public-api BFF (PUBLIC_API_URL)
// is reached at runtime — the Docker build has no cluster access.
export const revalidate = 3600

import { SimpleLayout } from '@/components/layout'
import { ProjectsList } from '@/components/projects'
import { ProjectCards, type ProjectCardData } from '@/components/projects/ProjectCards'
import { getAllArticles } from '@/lib/articles/article-service'
import { queryPublicProjects, projectTypeLabel } from '@/lib/projects'
import logoAws from '@/images/logos/aws.png'

import {
  Terminal,
  Server,
  Cloud,
  Database,
  Shield,
  GitBranch,
  Award,
  Cpu,
} from 'lucide-react'

// ========================================
// Legacy fallback: category → icon mapping for article-derived cards
// ========================================

/**
 * Maps article categories to lucide-react icons.
 * Articles without a matching category get the default Cloud icon.
 */
const categoryIcons: Record<string, ReactNode> = {
  'CI/CD': <GitBranch className="h-8 w-8 text-orange-400" />,
  'Infrastructure': <Server className="h-8 w-8 text-purple-400" />,
  'Security': <Shield className="h-8 w-8 text-red-400" />,
  'Monitoring': <Terminal className="h-8 w-8 text-green-400" />,
  'Certification': <Award className="h-8 w-8 text-teal-400" />,
  'Database': <Database className="h-8 w-8 text-yellow-400" />,
  'Compute': <Cpu className="h-8 w-8 text-blue-400" />,
}

/** Fallback icon for categories not in the map */
const defaultIcon = <Cloud className="h-8 w-8 text-blue-400" />

// ========================================
// Metadata
// ========================================

export const metadata: Metadata = {
  title: 'Projects | Nelson Lamounier, Cloud & DevOps Engineer',
  description:
    'Production AWS projects built with CDK, EKS Kubernetes, ArgoCD GitOps, Bedrock AI tooling, and full-stack observability. Each project includes an evidence-grounded case study: architecture, stack, key decisions, and challenges.',
}

// ========================================
// Page Component
// ========================================

/**
 * Projects page — fetches the owner's public Tucaken projects from the
 * BFF and renders them as case-study cards; falls back to article-derived
 * cards while the projects source is empty (see file header).
 */
export default async function Projects() {
  const publicProjects = await queryPublicProjects()

  if (publicProjects.length > 0) {
    const cards: ProjectCardData[] = publicProjects.map((p) => ({
      slug: p.slug,
      name: p.name,
      tagline: p.tagline,
      typeLabel: projectTypeLabel(p.type),
      // Stack names only — category grouping belongs on the detail page;
      // a card has room for chips, not a taxonomy.
      stack: p.stack.map((s) => s.name),
      repositories: p.repositories,
      tags: p.tags,
    }))
    const typeLabels = [...new Set(cards.map((c) => c.typeLabel))].sort(
      (a, b) => a.localeCompare(b),
    )

    return (
      <SimpleLayout
        title="What I've Built"
        intro="Everything here runs in production on AWS. Deployed from a CDK monorepo, delivered through ArgoCD GitOps on EKS, and monitored with Prometheus, Grafana, Loki, and Tempo. Each project links to an evidence-grounded case study generated from the repositories themselves: architecture, stack, key decisions, and the challenges behind them."
      >
        <ProjectCards projects={cards} typeLabels={typeLabels} />
      </SimpleLayout>
    )
  }

  // --- Legacy fallback: articles as project cards (pre-migration path) ---
  const articles = await getAllArticles()

  const projects = articles.map((article, index) => ({
    id: index + 1,
    title: article.title,
    description: article.description || article.aiSummary || '',
    tags: article.tags || [],
    category: article.category || 'Infrastructure',
    link: {
      href: `/articles/${article.slug}`,
      label: 'Read article',
    },
    icon: categoryIcons[article.category || ''] || defaultIcon,
    logo: logoAws,
  }))

  const uniqueCategories = [
    ...new Set(articles.map((a) => a.category || 'Infrastructure')),
  ].sort((a, b) => a.localeCompare(b))
  const categories = ['All', ...uniqueCategories]

  return (
    <SimpleLayout
      title="What I've Built"
      intro="Everything here runs in production on AWS. Deployed from a CDK monorepo, delivered through ArgoCD GitOps on self-managed Kubernetes, and monitored with Prometheus, Grafana, Loki, and Tempo. Each project links to a detailed article explaining the architecture, trade-offs, and what I'd do differently."
    >
      <ProjectsList projects={projects} categories={categories} />
    </SimpleLayout>
  )
}
