/** @format */

import { NextResponse } from 'next/server';
import { register } from '@/lib/observability/metrics';

// ========================================
// Bearer Token Authentication (SSM-backed)
// ========================================

/** SSM parameter path for the bearer token (set by monitoring EC2 at boot) */
const METRICS_TOKEN_SSM_PATH = process.env.METRICS_TOKEN_SSM_PATH || '';

/** Token cache TTL — avoids SSM API calls on every Prometheus scrape */
const TOKEN_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

/** How long to wait for SSM before giving up (prevents hanging) */
const SSM_TIMEOUT_MS = 3_000;

/** How long to wait before retrying after an SSM failure */
const SSM_RETRY_BACKOFF_MS = 60 * 1000; // 1 minute

let cachedToken: string | null = null;
let tokenFetchedAt = 0;
let lastFailureAt = 0;

/**
 * Retrieve the bearer token from SSM Parameter Store.
 * The token is generated by the monitoring EC2 at boot and stored as
 * a SecureString at /{namePrefix}/prometheus/metrics-bearer-token.
 *
 * Returns null (skip auth) when:
 * - METRICS_TOKEN_SSM_PATH is not configured
 * - SSM is unreachable (timeout after 3s)
 * - The parameter doesn't exist
 * - A recent SSM call already failed (backoff)
 */
async function getMetricsToken(): Promise<string | null> {
  // No SSM path configured — skip auth entirely
  if (!METRICS_TOKEN_SSM_PATH) {
    return null;
  }

  // Return cached token if still valid
  if (cachedToken && Date.now() - tokenFetchedAt < TOKEN_CACHE_TTL_MS) {
    return cachedToken;
  }

  // Back off if SSM recently failed (avoids hammering a broken path)
  if (lastFailureAt && Date.now() - lastFailureAt < SSM_RETRY_BACKOFF_MS) {
    return cachedToken; // return stale token or null
  }

  try {
    // Lazy-import SSM client to avoid loading it when auth is disabled
    const { SSMClient, GetParameterCommand } = await import('@aws-sdk/client-ssm');
    const ssm = new SSMClient({ region: process.env.AWS_REGION ?? 'eu-west-1' });

    // AbortController with 3s timeout prevents hanging when SSM is unreachable
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), SSM_TIMEOUT_MS);

    try {
      const result = await ssm.send(
        new GetParameterCommand({
          Name: METRICS_TOKEN_SSM_PATH,
          WithDecryption: true,
        }),
        { abortSignal: controller.signal },
      );

      cachedToken = result.Parameter?.Value ?? null;
      tokenFetchedAt = Date.now();
      lastFailureAt = 0; // reset failure state on success
      return cachedToken;
    } finally {
      clearTimeout(timeout);
    }
  } catch (err) {
    lastFailureAt = Date.now();
    console.warn(
      `[metrics] SSM token fetch failed (will retry in ${SSM_RETRY_BACKOFF_MS / 1000}s):`,
      err instanceof Error ? err.message : String(err),
    );
    // Return stale cached token if available, otherwise null (skip auth)
    return cachedToken;
  }
}

// ========================================
// GET /api/metrics
// ========================================

/**
 * GET /api/metrics
 * Returns metrics in Prometheus text format.
 *
 * Authentication:
 * - In production (ECS), validates a bearer token stored in SSM.
 * - In local dev (no SSM), falls through without auth.
 *
 * This endpoint is scraped by Prometheus every 15-30 seconds.
 */
export async function GET(request: Request) {
  try {
    // ── Bearer Token Validation ──
    const expectedToken = await getMetricsToken();

    if (expectedToken) {
      const authHeader = request.headers.get('authorization');

      if (authHeader !== `Bearer ${expectedToken}`) {
        return NextResponse.json(
          { error: 'Unauthorized' },
          { status: 401 },
        );
      }
    }

    // ── Return Prometheus Metrics ──
    const metrics = await register.metrics();

    return new NextResponse(metrics, {
      headers: {
        'Content-Type': register.contentType,
        'Cache-Control': 'no-store, no-cache, must-revalidate',
      },
    });
  } catch (error) {
    console.error('Error generating metrics:', error);

    // Return minimal metrics even on error
    return new NextResponse('# Error generating metrics\nnextjs_up 0\n', {
      status: 500,
      headers: {
        'Content-Type': 'text/plain; version=0.0.4',
      },
    });
  }
}

// Disable caching for metrics endpoint
export const dynamic = 'force-dynamic';
export const revalidate = 0;
