/** @format */

import { NextResponse } from 'next/server';
import { SSMClient, GetParameterCommand } from '@aws-sdk/client-ssm';
import { register } from '@/lib/metrics';

// ========================================
// Bearer Token Authentication (SSM-backed)
// ========================================

const ssm = new SSMClient({ region: process.env.AWS_REGION ?? 'eu-west-1' });

/** SSM parameter path for the bearer token (set by monitoring EC2 at boot) */
const METRICS_TOKEN_SSM_PATH =
  process.env.METRICS_TOKEN_SSM_PATH || '/nextjs/prometheus/metrics-bearer-token';

/** Token cache TTL — avoids SSM API calls on every Prometheus scrape */
const TOKEN_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

let cachedToken: string | null = null;
let tokenFetchedAt = 0;

/**
 * Retrieve the bearer token from SSM Parameter Store.
 * The token is generated by the monitoring EC2 at boot and stored as
 * a SecureString at /{namePrefix}/prometheus/metrics-bearer-token.
 *
 * Returns null if:
 * - SSM is unreachable (local dev, missing IAM permissions)
 * - The parameter doesn't exist yet (monitoring stack not deployed)
 *
 * When null, the endpoint falls through without auth (allows local dev).
 */
async function getMetricsToken(): Promise<string | null> {
  if (cachedToken && Date.now() - tokenFetchedAt < TOKEN_CACHE_TTL_MS) {
    return cachedToken;
  }

  try {
    const result = await ssm.send(
      new GetParameterCommand({
        Name: METRICS_TOKEN_SSM_PATH,
        WithDecryption: true,
      }),
    );
    cachedToken = result.Parameter?.Value ?? null;
    tokenFetchedAt = Date.now();
    return cachedToken;
  } catch {
    // SSM unreachable or parameter doesn't exist — no auth enforced
    return null;
  }
}

// ========================================
// GET /api/metrics
// ========================================

/**
 * GET /api/metrics
 * Returns metrics in Prometheus text format.
 *
 * Authentication:
 * - In production (ECS), validates a bearer token stored in SSM.
 * - In local dev (no SSM), falls through without auth.
 *
 * This endpoint is scraped by Prometheus every 15-30 seconds.
 */
export async function GET(request: Request) {
  try {
    // ── Bearer Token Validation ──
    const expectedToken = await getMetricsToken();

    if (expectedToken) {
      const authHeader = request.headers.get('authorization');

      if (authHeader !== `Bearer ${expectedToken}`) {
        return NextResponse.json(
          { error: 'Unauthorized' },
          { status: 401 },
        );
      }
    }

    // ── Return Prometheus Metrics ──
    const metrics = await register.metrics();

    return new NextResponse(metrics, {
      headers: {
        'Content-Type': register.contentType,
        'Cache-Control': 'no-store, no-cache, must-revalidate',
      },
    });
  } catch (error) {
    console.error('Error generating metrics:', error);

    // Return minimal metrics even on error
    return new NextResponse('# Error generating metrics\nnextjs_up 0\n', {
      status: 500,
      headers: {
        'Content-Type': 'text/plain; version=0.0.4',
      },
    });
  }
}

// Disable caching for metrics endpoint
export const dynamic = 'force-dynamic';
export const revalidate = 0;
