/**
 * Content Schemas — Zod Runtime Validation
 *
 * These schemas validate content at runtime, ensuring that
 * generateMetadata(), JSON-LD scripts, and API responses never
 * break due to malformed data from DynamoDB or S3.
 *
 * Every schema mirrors a TypeScript interface from content-blocks.ts
 * and article.types.ts — Zod infers the type so they stay in sync.
 */

import { z } from 'zod'

// ========================================
// Article Metadata Schema
// ========================================

/**
 * Validates DynamoDB "Brain" metadata before feeding to
 * generateMetadata() and JSON-LD generation.
 */
export const ArticleMetadataSchema = z.object({
  slug: z.string().min(1),
  title: z.string().min(1).max(200),       // Allow longer AI-generated titles
  description: z.string().default(''),     // Bedrock may omit — fall back to aiSummary in UI
  author: z.string().default('Nelson Lamounier'),
  date: z.string().default(() => new Date().toISOString().slice(0, 10)),
  tags: z.array(z.string()).default([]),
  category: z.string().optional(),
  heroImageUrl: z.string().url().optional(),
  aiSummary: z.string().optional(),
  contentRef: z.string().min(1),
  readingTimeMinutes: z.number().int().positive().optional(),
  status: z.enum(['draft', 'published', 'archived']).default('published'),
})

/** Inferred type from Zod — use this instead of manually defining */
export type ValidatedArticleMetadata = z.infer<typeof ArticleMetadataSchema>

// ========================================
// Image Sidecar Schema
// ========================================

/**
 * Validates the JSON sidecar fetched alongside images from S3.
 * Generated by the Bedrock pipeline with AI-produced alt text.
 */
export const ImageSidecarSchema = z.object({
  alt: z.string().min(1),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  blurHash: z.string().optional(),
  caption: z.string().optional(),
})

export type ValidatedImageSidecar = z.infer<typeof ImageSidecarSchema>

// ========================================
// Content Block Schemas (Discriminated Union)
// ========================================

const BaseBlockSchema = z.object({
  id: z.string().min(1),
  position: z.number().int().nonnegative(),
})

const CodeSnippetSchema = BaseBlockSchema.extend({
  type: z.literal('code-snippet'),
  language: z.string().min(1),
  code: z.string().min(1),
  filename: z.string().optional(),
  highlights: z.array(z.number().int().nonnegative()).optional(),
})

const ArchitectureDiagramSchema = BaseBlockSchema.extend({
  type: z.literal('architecture-diagram'),
  chart: z.string().min(1),
  caption: z.string().optional(),
})

const SecurityPolicySchema = BaseBlockSchema.extend({
  type: z.literal('security-policy'),
  severity: z.enum(['critical', 'high', 'medium', 'low']),
  title: z.string().min(1),
  description: z.string().min(1),
  remediation: z.string().optional(),
})

const ProcessTimelineSchema = BaseBlockSchema.extend({
  type: z.literal('process-timeline'),
  steps: z
    .array(
      z.object({
        title: z.string().min(1),
        description: z.string().min(1),
      }),
    )
    .min(1),
})

const CalloutSchema = BaseBlockSchema.extend({
  type: z.literal('callout'),
  variant: z.enum(['info', 'warning', 'security', 'insight']),
  title: z.string().min(1),
  content: z.string().min(1),
})

const SmartImageSchema = BaseBlockSchema.extend({
  type: z.literal('smart-image'),
  src: z.string().min(1),
  sidecarUrl: z.string().optional(),
  caption: z.string().optional(),
})

/**
 * Discriminated union schema for all content block types.
 * Use this to validate individual blocks from the Bedrock pipeline.
 */
export const ContentBlockSchema = z.discriminatedUnion('type', [
  CodeSnippetSchema,
  ArchitectureDiagramSchema,
  SecurityPolicySchema,
  ProcessTimelineSchema,
  CalloutSchema,
  SmartImageSchema,
])

export type ValidatedContentBlock = z.infer<typeof ContentBlockSchema>

// ========================================
// Validation Helpers
// ========================================

/**
 * Validate and type-narrow article metadata at runtime.
 * Throws ZodError with detailed path info on failure.
 *
 * @example
 * ```ts
 * const metadata = validateMetadata(dynamoDbItem)
 * // metadata is now ValidatedArticleMetadata
 * ```
 */
export function validateMetadata(raw: unknown): ValidatedArticleMetadata {
  return ArticleMetadataSchema.parse(raw)
}

/**
 * Safe validation that returns a result instead of throwing.
 * Use this when you want to handle invalid data gracefully
 * (e.g., logging a warning instead of crashing the page).
 */
export function safeValidateMetadata(raw: unknown) {
  return ArticleMetadataSchema.safeParse(raw)
}

/**
 * Validate an image sidecar fetched from S3.
 * Throws ZodError on invalid data.
 */
export function validateSidecar(raw: unknown): ValidatedImageSidecar {
  return ImageSidecarSchema.parse(raw)
}

/**
 * Safe sidecar validation — returns `{ success, data?, error? }`.
 */
export function safeValidateSidecar(raw: unknown) {
  return ImageSidecarSchema.safeParse(raw)
}

/**
 * Validate a single content block.
 * Throws ZodError if the block type is unrecognized or data is invalid.
 */
export function validateContentBlock(raw: unknown): ValidatedContentBlock {
  return ContentBlockSchema.parse(raw)
}

/**
 * Validate an array of content blocks, filtering out invalid ones
 * and logging warnings for each failure.
 */
export function validateContentBlocks(
  rawBlocks: unknown[],
): ValidatedContentBlock[] {
  const validated: ValidatedContentBlock[] = []

  for (const block of rawBlocks) {
    const result = ContentBlockSchema.safeParse(block)
    if (result.success) {
      validated.push(result.data)
    } else {
       
      console.warn(
        '[content-schemas] Invalid content block skipped:',
        JSON.stringify(result.error.issues),
      )
    }
  }

  return validated
}
