/**
 * Content Block Types — Discriminated Unions
 *
 * The "Gold Standard" for typed content. Each block has a `type`
 * discriminator that lets TypeScript narrow to the correct shape
 * at compile time — and lets the AI pipeline distinguish between
 * a "Code Snippet," an "Architecture Diagram," and a "Security Policy."
 *
 * These types describe the structured blocks that appear within
 * S3-hosted MDX articles. File-based articles use JSX components
 * directly and don't need these types.
 */

// ========================================
// Base Block
// ========================================

export interface BaseBlock {
  /** Unique identifier within the article */
  id: string
  /** Ordinal position in the article body */
  position: number
}

// ========================================
// Discriminated Union — ContentBlock
// ========================================

/**
 * A single content block within an article.
 * Discriminated on `type` for exhaustive pattern matching.
 */
export type ContentBlock =
  | CodeSnippetBlock
  | ArchitectureDiagramBlock
  | SecurityPolicyBlock
  | ProcessTimelineBlock
  | CalloutBlock
  | SmartImageBlock

// ─── Code Snippet ───

export interface CodeSnippetBlock extends BaseBlock {
  type: 'code-snippet'
  /** Language identifier for syntax highlighting (e.g., 'typescript', 'python') */
  language: string
  /** The raw code string */
  code: string
  /** Optional filename shown above the code block */
  filename?: string
  /** Optional line numbers to highlight */
  highlights?: number[]
}

// ─── Architecture Diagram ───

export interface ArchitectureDiagramBlock extends BaseBlock {
  type: 'architecture-diagram'
  /** Mermaid DSL chart definition */
  chart: string
  /** Optional caption shown below the diagram */
  caption?: string
}

// ─── Security Policy ───

export interface SecurityPolicyBlock extends BaseBlock {
  type: 'security-policy'
  /** Severity classification */
  severity: 'critical' | 'high' | 'medium' | 'low'
  /** Policy title */
  title: string
  /** Policy description or finding detail */
  description: string
  /** Optional remediation guidance */
  remediation?: string
}

// ─── Process Timeline ───

export interface ProcessTimelineBlock extends BaseBlock {
  type: 'process-timeline'
  /** Ordered steps in the timeline */
  steps: ProcessStep[]
}

export interface ProcessStep {
  title: string
  description: string
}

// ─── Callout ───

export interface CalloutBlock extends BaseBlock {
  type: 'callout'
  /** Visual variant */
  variant: 'info' | 'warning' | 'security' | 'insight'
  /** Callout title */
  title: string
  /** MDX-safe content string */
  content: string
}

// ─── Smart Image ───

export interface SmartImageBlock extends BaseBlock {
  type: 'smart-image'
  /** CloudFront/S3 image URL */
  src: string
  /** JSON sidecar URL — auto-derived from src if omitted */
  sidecarUrl?: string
  /** Optional caption shown below the image */
  caption?: string
}

// ========================================
// Image Sidecar (fetched from S3)
// ========================================

/**
 * JSON sidecar stored alongside each image in S3.
 * Generated by the Bedrock pipeline with AI-produced alt text.
 */
export interface ImageSidecar {
  /** Descriptive alt text (AI-generated) */
  alt: string
  /** Image width in pixels */
  width: number
  /** Image height in pixels */
  height: number
  /** Optional BlurHash for placeholder */
  blurHash?: string
  /** Optional caption */
  caption?: string
}

// ========================================
// SmartImage Props (for the RSC component)
// ========================================

export interface SmartImageProps {
  /** CloudFront/S3 image URL */
  src: string
  /** Fallback alt text if sidecar fetch fails */
  fallbackAlt?: string
  /** Optional CSS class */
  className?: string
  /** Optional caption override (takes precedence over sidecar caption) */
  caption?: string
}

// ========================================
// Utility: Exhaustive Block Renderer
// ========================================

/**
 * Helper for exhaustive switch over ContentBlock.type.
 * TypeScript will error if a new block type is added but not handled.
 */
export function assertNever(x: never): never {
  throw new Error(`Unhandled content block type: ${JSON.stringify(x)}`)
}
